---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: VM_IMPORT_FROM_CONFIGURATION_EXECUTED_SUCCESSFULLY
    inherits: 
    description: 
  fields:
  - rel4:
      value: "/System/event_handlers/refresh"
