---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: ReconfigVM_Task_Complete
    inherits: 
    description: 
  fields:
  - rel4:
      value: "/System/Event/StateMachines/Refresh/default?refresh_target=src_vm&policy_event=vm_reconfigure&policy_target=src_vm"
