---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: InfrastructureConfiguredSystemMiqProvisionRequestApproverApproved
    inherits: 
    description: 
  fields:
  - mail_method:
      value: "#stop_email"
