---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: MiqProvisionConfiguredSystemRequest_pending
    inherits: 
    description: 
  fields:
  - rel5:
      value: "/System/Notification/Email/InfrastructureConfiguredSystemMiqProvisionRequestRequesterPending"
  - rel6:
      value: "/System/Notification/Email/InfrastructureConfiguredSystemMiqProvisionRequestApproverPending"
