---
object_type: instance
version: 1.0
object:
  attributes:
    display_name: 
    name: VmCloudReconfigureRequest_created
    inherits: 
    description: 
  fields:
  - meth5:
      value: vmcloudreconfigure_request_auto_approve
